### ISSUE TITLE
Slow db creation

### ISSUE THREAD

**Issue by HadrienG** [HadrienG/taxadb#10]
Since the last release, the database creation is (very) slow.

It would be nice to add a `--fast` option that disables some checks to speed up the db creation (useful  if we're creating the db for the first time)

**Comment by horkko** [comment]
@HadrienG This might be cause by the fact that the table `accession` is created with an index on `accession.accession` column. If could be faster to remove this index, load the data, then recreate the index.

**Comment by HadrienG** [comment]
I did some preliminary testing and it seems to be the db calls to check if the Accession number is already in the db that take a lot of time.

In the `try / except` block in `parse.py` line 243:
 ```python
acc_id = Accession.get(Accession.accession == line_list[0])
```

Checking for existing entries is not really necessary if you are creating the db for the first time (given we trust the ncbi with the input files).

**Comment by horkko** [comment]
Hi,
I agree with you, it does not make sense at db creation. However, it may prevent if a user stopped a loading and redo it. It also prevent people to reload the same file, it avoids error.
But I agree with you. We could remove this check? Or add an option `--init` or whatever?

**Comment by HadrienG** [comment]
I think making in a non-default option makes the most sense (`--fast` or `--init` like you said).

It would allow for fast db creation, would allow users to resume a stopped db creation (although given the speed gain it think it'd be faster to restart the whole process with the `--init` option)

And if a user would mistakenly run `taxadb create` on an existing db, the default behavior would still be to check for existing accessions, so no overriding or errors!

I'll add the option this week

**Comment by horkko** [comment]
Ok, great speed up without `try/except` block indeed.
I let you install this new option.
By the way, chek my repo, I've created a new branch `config` which add use of configuration and/or environment variable for settings database connection parameters. I've also added corresponding tests, but still some to add to reach 100% coverage :smiley:

**Comment by horkko** [comment]
Hi Hadrien,

May I merge your branch `fast_create` into mine `config`?

**Comment by tbigot** [comment]
Indeed, it’s faster using 76ca4bb30a904f44edc93b1e6c0f803152f977f9.
But the way it worked before this commit consists in two distinct SQL queries.
I guess letting the SGDB doing the check itself *while* inserting could really improve the speed. For instance, with SQLITE (http://www.sqlite.org/lang_conflict.html):
```sql
INSERT ON CONFLICT IGNORE
```
It has been shown doing this way strongly improve performances http://stackoverflow.com/questions/15523442/what-is-the-reason-for-sqlite-upsert-performance-improvment-with-unique-on-confl

Reason is `INSERT ON CONFLICT IGNORE` queries the index *only once*. Whereas checking and then inserting need two checks.

**Comment by horkko** [comment]
@tbigot That could be a good alternative, however this example is for SQLite only. And taxadb supports PosgreSQL and MySQL. Fortunately, this SQL syntax is also supported by PostgreSQL (https://www.postgresql.org/docs/9.5/static/sql-insert.html) but only for pg 9.5+. People with earlier version won't be able to use taxadb.
Last, MySQL does not support such constraint, the only thing possible is
 ```sql
 ON DUPLICATE KEY UPDATE
```
 (https://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html)
 which means an update for every duplicate value.

Moreover, sqlite use this at table schema creation, whereas Postgresql use it inside an `INSERT` statement such as MySQL. And we do not know how `peewee` handle these cases. Maybe we need to check and test.

**Comment by tbigot** [comment]
@horkko I suspected that peewee may not be able to handle such diversity. It’s an intrinsic limitation of that kind of tool I guess. Since db creation is a very specific step, and won’t concern a lot of users (many of them will be tempted by the already made db, I suppose), it could maybe be natively written in each SGBD language (SQLITE / Postgres / MySQL…), allowing this kind of optimization. What do you think?

**Comment by horkko** [comment]
@tbigot I think it is not as simple as that. I think we could update the SQL script provided to build the database for taxadb for PostgreSQL and MySQL. However, for SQLite, this optimization applies at the `INSERT` command, which is "specific" case for our supported RDBMS and cannot (not 100% sure) be handled by peewee. Unless we specify a raw SQL query to be triggered by peewee which thus means a specific piece of code for this RDBMS. I don't think this was the first intention by @HadrienG 
I let @HadrienG answering this point then.

**Comment by HadrienG** [comment]
peewee apparently supports `on_conflict`, so we could speed up db updates for sqlite (and maybe for postgres.

I'm not a big fan of writing queries in sql natively, the strengths of peewee (or other ORMs) is that it is simple and intuitive. Having three different languages to care about would be tricky to handle and debug.

**Comment by horkko** [comment]
Yes it is supported but for sqlite only :cry:  http://docs.peewee-orm.com/en/latest/peewee/api.html#UpdateQuery.on_conflict

**Comment by HadrienG** [comment]
A `--fast` option has been added in 0.6.0. I'll close this since IMO it solves the issue, but will keep the `on_conflict` idea in mind.
