### ISSUE TITLE
Current DB proposed for download won’t work with current version

### ISSUE THREAD

**Issue by tbigot** [HadrienG/taxadb#13]
Hi,
Since db schema has changed, the current DBs proposed for download won’t work with current version of taxadb.
I’ve rebuilt the full db today, with NCBI data extracted mid-February:
```
parsed nodes
parsed names
merge successful
Taxa: completed
accession: nucl_est.accession2taxid.gz added to database (75680789 rows inserted)
accession: nucl_gb.accession2taxid.gz added to database (108007772 rows inserted)
accession: nucl_gss.accession2taxid.gz added to database (39772399 rows inserted)
accession: nucl_wgs.accession2taxid.gz added to database (352349395 rows inserted)
accession: prot.accession2taxid.gz added to database (360054250 rows inserted)
Sequence: completed
```
Here is the file: http://dl.pasteur.fr/fop/3K5BAvZM/taxadb.sqlite3.gz

**Comment by horkko** [comment]
@tbigot Thanks :+1:

**Comment by tbigot** [comment]
I’ve just launched rebuild of all division db including `full` with today’s NCBI data.

**Comment by HadrienG** [comment]
Hi!

Thank you!

I've actually just finished re-building all the version of the sqlite databases. I'll make them available asap if you don't want to rebuild everything yourself.

**Comment by tbigot** [comment]
@horkko I’m sorry, but in the file I provided, there is no index. I’ve simply generated it with taxadb --fast option, is it expected?
@HadrienG Ok, fine! Maybe yours will be correctly indexed! ;-)
(I’m checking what’s wrong at my side)

**Comment by HadrienG** [comment]
Good catch!

And the index is gone in `master` too. Apparently `index=true` was removed from the schema in 34215d562118f711722971cebae88ecbe4c51966 and `db.create_index(Accession, ['accession'], unique=True)` was removed from `app.py` in 507efe971feca1f07953c2b8d7f536ef3e97febb

I'm unsure if we need `index=true` since we want to index after filling the db. I'll add `db.create_index()` in `app.py` and see if it fixes the problem

**Comment by horkko** [comment]
@HadrienG @tbigot Yes `db.create_index(Accession, ['accession'], unique=True)` has been removed because `schema.Accession` has the field option `unique=True` which (from the documentation) adds a unique index on the column : http://docs.peewee-orm.com/en/latest/peewee/models.html#indexes-and-constraints and http://docs.peewee-orm.com/en/latest/peewee/models.html?highlight=create_index#field-initialization-arguments

So for me, the index should be automatically created when table is created. That's why `db.create_index` should not be called again.

**Comment by horkko** [comment]
@tbigot @HadrienG Ok this is my fault. The index should be created as it was before like `db.create_index(Accession, ['accession'], unique=True)`. Only given argument field `unique=True` for table `Accession` does not automatically create the index as I though. Proof below:
```python
from taxadb.schema import *

database = DatabaseFactory(dbtype='sqlite', dbname='/data/sqlite3/new_db.sqlite').get_database()
db.initialize(database)
db.connect()
db.create_table(Taxa, safe=True)
db.create_table(Accession, safe=True)
Taxa.create(ncbi_taxid=1, parent_taxid=0, tax_name='manu', lineage_level='rank')
Accession.create(id=1, taxid_id=1, accession='X1234')
```
After this point, the index is not created at all in sqlite:
```sqlite3
sqlite> .schema
CREATE TABLE "taxa" ("ncbi_taxid" INTEGER NOT NULL PRIMARY KEY, "parent_taxid" INTEGER NOT NULL, "tax_name" VARCHAR(255) NOT NULL, "lineage_level" VARCHAR(255) NOT NULL);
CREATE TABLE "accession" ("id" INTEGER NOT NULL PRIMARY KEY, "taxid_id" INTEGER NOT NULL, "accession" VARCHAR(255) NOT NULL, FOREIGN KEY ("taxid_id") REFERENCES "taxa" ("ncbi_taxid"));
sqlite> select * from taxa;
1|0|manu|rank
sqlite> select * from accession;     
1|1|X1234
```

My fault, my misunderstanding.

**Comment by horkko** [comment]
Code also tested on postgres, same behaviour, no index created.

**Comment by horkko** [comment]
It could be catched this way?:

```python
    print('%s: %s added to database (%d rows inserted)' % (
                Accession.get_table_name(), acc_file, inserted_rows))
        try:
            db.create_index(Accession, ['accession'], unique=True)
        except PeeweeException as err:
            raise Exception("Could not create Accession.accession index: %s"
                            % str(err))
```

**Comment by HadrienG** [comment]
I didn't bother with a `try` block but yes 😄 

tha last commit in the `fast_create` branch should fix the indexes

**Comment by tbigot** [comment]
@horkko Indeed, with `unique`, there is an index on primary key. But index is set on inner `id`, whereas the column `accession` should be the primary key. To my mind, a unique `id` is not relevant since we really want to index and to identify the rows with their accession number, and we do not use this integer `id`.

**Comment by horkko** [comment]
@tbigot You're right, `id` is not used at all. We could remove it. @HadrienG what do you think. I've kept it when I've merged tables for compat.

**Comment by horkko** [comment]
@HadrienG I've merged your branch `fast_create` into mine `config`. I've rebuild the `full` division database in 287min! using `--fast` option. Here is the output:
```sh
(taxadb) tuco@bidule [08:44:23] taxadb (fast_create) $ time taxadb --verbose create --chunk 10000 --input ../db/ --dbname /data/sqlite3/taxadb_full2.sqlite --dbtype sqlite --division full --fast
[VERBOSE] Connected to database ...
[VERBOSE] Creating table taxa
parsed nodes
parsed names
merge successful
Taxa: completed
[VERBOSE] Parsing nucl_est.accession2taxid.gz
[VERBOSE] Parsing ../db/nucl_est.accession2taxid.gz
[VERBOSE] Fast mode ON
accession: nucl_est.accession2taxid.gz added to database (75663361 rows inserted)
[VERBOSE] Parsing nucl_gb.accession2taxid.gz
[VERBOSE] Parsing ../db/nucl_gb.accession2taxid.gz
[VERBOSE] Fast mode ON
accession: nucl_gb.accession2taxid.gz added to database (107083701 rows inserted)
[VERBOSE] Parsing nucl_gss.accession2taxid.gz
[VERBOSE] Parsing ../db/nucl_gss.accession2taxid.gz
[VERBOSE] Fast mode ON
accession: nucl_gss.accession2taxid.gz added to database (39765090 rows inserted)
[VERBOSE] Parsing nucl_wgs.accession2taxid.gz
[VERBOSE] Parsing ../db/nucl_wgs.accession2taxid.gz
[VERBOSE] Fast mode ON
accession: nucl_wgs.accession2taxid.gz added to database (347514070 rows inserted)
[VERBOSE] Parsing prot.accession2taxid.gz
[VERBOSE] Parsing ../db/prot.accession2taxid.gz
[VERBOSE] Fast mode ON
accession: prot.accession2taxid.gz added to database (340073320 rows inserted)
Creating index for accession
Accession: completed

real    278m7.125s
user    274m59.968s
sys     1m2.604s
```
Total size for database is 38Gb.
I think we are close :)
May I create a PR for the new branch `config`? (Which will actually be a merge of `fast_create` and `config`)

Emmanuel
