### ISSUE TITLE
URLs broken for SQLite3 databases

### ISSUE THREAD

**Issue by jorvis** [HadrienG/taxadb#14]
I'm getting 404 errors for any of the SQLite3 database downloads, such as:

http://139.162.178.46/files/taxadb/taxadb_gb.sqlite.gz

Have you considered using [Git Large File Storage](https://git-lfs.github.com/)?

**Comment by HadrienG** [comment]
Hi!

Unfortunately I don't have the possibility to store the files in house anymore. I looked at git lfs but github's plans seem expensive.

Building the database should take you less than a day though.

Best,
Hadrien
