### ISSUE TITLE
Failure to build sqlite3 database

### ISSUE THREAD

**Issue by Erotemic** [HadrienG/taxadb#16]
You should change the sqlite command for building the database in the docs from `taxadb create -i taxadb --dbname taxadb` to `taxadb create -i taxadb --dbname taxadb.sqlite`. Otherwise it raises an error 

`peewee.OperationalError: unable to open database file` because the name of the download folder and sqlite database conflict.

**Comment by HadrienG** [comment]
Thanks for reporting this! I'll change the documentation accordingly
