### ISSUE TITLE
Allow taxa names as input to obtain the corresponding taxa id

### ISSUE THREAD

**Issue by RVanDamme** [HadrienG/taxadb#19]
It would be great to be able to submit a list of taxnames and obtain an output of the corresponding taxids. The NCBI has a web tool for that (https://www.ncbi.nlm.nih.gov/Taxonomy/TaxIdentifier/tax_identifier.cgi).
I think it would be a nice addition to taxadb.

**Comment by HadrienG** [comment]
implemented in branch `names`. It will be part of 0.8.0

**Comment by HadrienG** [comment]
Addressed in `0.8.0`. Not completely sure about the interface on this one. `SciName` may be merged with TaxId` in the future, or will stay its own class.

Anyway the function is there and documented!
