### ISSUE TITLE
no rank issue

### ISSUE THREAD

**Issue by alienzj** [HadrienG/taxadb#46]
So great tool ! Thank HadrienG !

I have use taxadb to build a ncbi taxonomy database.
When I search taxid 1236518, I found some problem.

![image](https://user-images.githubusercontent.com/8847420/60082758-fe467700-9766-11e9-9487-ce0600ed4681.png)

When I search taxid [589437](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=589437),
we can find taxid [1236518](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=1236518)

So, I thank the "no rank" should  to be 1236518, not 131567.

**Comment by HadrienG** [comment]
Hi!

Thanks for the bug report. I'm currently on vacation but I'll look into it when I'm back.

Best,
Hadrien.

**Comment by HadrienG** [comment]
taxadb 0.12.0 now returns a list of tuple and should include all the `no rank` fields correctly.
