### ISSUE TITLE
Shouldn’t accessions table be merged in a unique one?

### ISSUE THREAD

**Issue by tbigot** [HadrienG/taxadb#5]
Since indexation dramatically increased performances, shouldn’t all accession numbers be in the same table, since they are unique identifiers?

**Comment by HadrienG** [comment]
Hi!

This was my original idea, but at the time I was still playing around with peewee, and building the database with only one big `accession` table was taking way too long.

I should give it a try now that the process has been somewhat optimised with transactions and chunk sizes. I will keep this issue opened and keep you updated 🙂

**Comment by HadrienG** [comment]
Hi,

Version 0.5.0 of the package has been released, and tables have been merged into one big `accession` table.
