### ISSUE TITLE
Problems building/querying database: Can't create database object: 'None' not supported

### ISSUE THREAD

**Issue by nextgenusfs** [HadrienG/taxadb#67]
Not sure what the problem is, but this is the error I'm getting:
```
>>> from taxadb.taxid import TaxID
>>> taxid = TaxID(dbype='sqlite', dbname='/path/to/taxadb.taxa.sqlite')
Can't create database object: Database type 'None' not supported
```
To create the database, I ran these commands that all ran without error:
```
$ taxadb download -o taxadb --type taxa -f
$ taxadb create -i taxadb/ --division taxa --dbname taxadb.taxa.sqlite
```

**Comment by HadrienG** [comment]
Hi!

You cannot create the database using the python API, you have to use the command-line tool for that. Once you've created your database with `taxadb create`, you should be able to connect to it using the python library.

Note that you have a typo in your code snipper, `dbype` should be `dbtype`! I agree however that the error message could be more useful.

Hope that helps!
Best,
Hadrien

**Comment by nextgenusfs** [comment]
Geez how embarrassing! Was likely the typo as I did build database from command line. Thanks!
